### ISSUE TITLE
function name conflict in particles2.c

### ISSUE THREAD

**Issue by carlodefalco** [cburstedde/p4est#88]
Hi,

I'm trying to compile on macos 11.1 and get a functio naming conflict in particles2.c : 

`../p4est/example/particles/particles2.c:1718:1: error: static declaration of 'wait' follows non-static declaration
wait (part_global_t * g)`

the previous definition comes from the system header sys/wait.h which is included by stdlib.h which is included by sc.h

a simple solution is to just change the name of the wait function to something less common, e.g.:

    diff --git a/example/particles/particles2.c b/example/particles/particles2.c
    index e45130ba..8ec3a7f3 100644
    --- a/example/particles/particles2.c
    +++ b/example/particles/particles2.c
    @@ -1715,7 +1715,7 @@ pprint (part_global_t * g, double t)
     }
     
     static void
    -wait (part_global_t * g)
    +particles_wait (part_global_t * g)
     {
       int                 mpiret;
       int                 i;
    @@ -2375,7 +2375,7 @@ sim (part_global_t * g)
           regroup (g);
     
           /* wait for sent messages to complete */
    -      wait (g);
    +      particles_wait (g);
     
           /* if no refinement occurred, store received particles and break loop */

but maybe one dose not need to pollute the global namespace with all definitions from stdlib.h ?

Notice that this issue is not specific to macos 11.1 (or more precisely XCode 12) it is just showing
up on this new system because in the latest release Apple made the option 

    -Werror=implicit-function-declaration

on by default. It should be possible to trigger the same error on other systems by adding the
above option to CFLAGS.

**Comment by cburstedde** [comment]
Hi, thanks, this issue has been resolved in the develop and prev3-develop branches. The former is more backwards compatible than the latter, but the latter gets rid of a lot of unneeded dependencies. Could you try one of those?

**Comment by carlodefalco** [comment]
Hi, I tested the develop branch and it works now, thanks!
